version: '3'
# TODO: setup prometheus and grafana containers
services:
  db:
    container_name: redirect_db
    build: ./db/
    ports:
      - "3308:3306"
    volumes:
#      Uncomment next line to run custom database scripts e.g. users, permissions, etc.
#      - ./db/setup:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
#      Uncomment next line to persist the database into your local system
#      - ./db/data/mysql:/var/lib/mysql
    env_file:
      - ./db/local.env
    tty: true
  api:
    container_name: redirect_api
    depends_on:
      - db
    build: ./api
    ports:
      - "8006:8006"
    restart: unless-stopped
    tty: true
    volumes:
      - ./api:/app
    env_file:
      - ./api/local.env
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - 3000:3000
#    volumes:
#      - grafana_data:/var/lib/grafana



